#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
pwd
echo "building..."
if ! mvn clean package > build.log 2> build.err.log; then
	echo "failed to build - see build.log"
	exit 1
fi
echo "succeeded - see build.log"