#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
pwd
echo "building birt-spring-boot..."
if ! mvn clean package > build.log 2> build-root.err.log; then
	echo "failed to build birt-spring-boot - see build.log"
	exit 1
fi
echo "birt-spring-boot build succeeded - see build.log"
if ! ./mvn-install-local; then
	exit 1
fi
echo "install succeeded - see install.log"
if ! ./birt-simple/build "0.0.5-SNAPSHOT"; then
	exit 1
fi
