#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
pwd
echo "building birt-spring-boot..."
if ! mvn clean package > build.log 2> build-root.err.log; then
	echo "failed to build birt-spring-boot - see build.log"
	exit 1
fi
echo "birt-spring-boot build succeeded - see build.log"
if ! ./mvn-install-local; then
	exit 1
fi
echo "install succeeded - see install.log"
cd birt-engine-sample-app
if ! mvn clean package > build.log 2> build.err.log; then
	echo "failed to build sample app - see birt-engine-sample-app/build.log"
	exit 1
fi
echo "sample app build succeeded - see birt-engine-sample-app/build.log"
cd ..
cd birt-engine-sample-app-full
if ! mvn clean package > build.log 2> build.err.log; then
	echo "failed to build full sample app - see birt-engine-sample-app-full/build.log"
	exit 1
fi
echo "full sample app build succeeded - see birt-engine-sample-app-full/build.log"
