version: '3.1'

services:

  birtengine:
    image: verseData/birt_engine
    build:
      context: ./
      dockerfile: Dockerfile  
    restart: always
    ports:
      - 8989:8080
      - 9090:8081  
