#!/bin/sh
FULLFILENAME=$1
BASENAME=$(basename "$FULLFILENAME")
ARTIFACT_ID="${BASENAME%.*}"
mvn install:install-file \
  -Dfile=$FULLFILENAME \
  -DgroupId=com.innoventsolutions.birt-spring-boot-modules \
  -DartifactId=$ARTIFACT_ID \
  -Dversion=0.0.1 \
  -Dpackaging=jar \
  -DgeneratePom=true
