#!/bin/sh
cd "$(dirname "${BASH_SOURCE[0]}")"
mvn install:install-file \
  -Dfile="./pom.xml" \
  -DgroupId="com.innoventsolutions.birt-spring-boot" \
  -DartifactId="birt-spring-boot" \
  -Dversion=0.0.1-SNAPSHOT \
  -Dpackaging=pom \
  -DgeneratePom=false
mvn install:install-file \
  -Dfile="./birt-spring-boot-starter/target/birt-spring-boot-starter-0.0.1-SNAPSHOT.jar" \
  -DgroupId="com.innoventsolutions.birt-spring-boot" \
  -DartifactId="birt-spring-boot-starter" \
  -Dversion=0.0.1-SNAPSHOT \
  -Dpackaging=jar \
  -DgeneratePom=false
mvn install:install-file \
  -Dfile="./birt-spring-boot-starter/pom.xml" \
  -DgroupId="com.innoventsolutions.birt-spring-boot" \
  -DartifactId="birt-spring-boot-starter" \
  -Dversion=0.0.1-SNAPSHOT \
  -Dpackaging=pom \
  -DgeneratePom=false
mvn install:install-file \
  -Dfile="./birt-engine/target/birt-engine-0.0.1-SNAPSHOT.jar" \
  -DgroupId="com.innoventsolutions.birt-spring-boot" \
  -DartifactId="birt-engine" \
  -Dversion=0.0.1-SNAPSHOT \
  -Dpackaging=jar \
  -DgeneratePom=true
mvn install:install-file \
  -Dfile="./birt-engine-autoconfig/target/birt-spring-boot-autoconfigure-0.0.1-SNAPSHOT.jar" \
  -DgroupId="com.innoventsolutions.birt-spring-boot" \
  -DartifactId="birt-spring-boot-autoconfigure" \
  -Dversion=0.0.1-SNAPSHOT \
  -Dpackaging=jar \
  -DgeneratePom=true
