#!/bin/sh
SUSPEND="n"
while (( "$#" )); do
	case $1 in
		suspend)
			SUSPEND="y"
			;;
		*)
			echo "Unrecognized argument"
			exit 1
			;;
	esac
	shift
done
cd $HOME/projects/birt-spring-boot-starter-mvn
echo "building..."
if ! mvn clean package > build.log 2> build.err.log; then
	echo "failed to build - see build.log"
	exit 1
fi
echo "running..."
JAR="./birt-engine-sample-app-full/target/birt-engine-sample-app-full-0.0.1-SNAPSHOT.jar"
java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=$SUSPEND,address=8000 -jar "$JAR" > run.log 2> run.err.log &
echo "kill $!" > stop
chmod u+x stop