#!/bin/sh
cd $HOME/projects/birt-spring-boot-starter-mvn
if [ mvn clean package > build.log 2> build.err.log ]; then
	echo "running..."
	java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000 -jar ./birt-engine-sample-app/target/birt-engine-test-0.0.1-SNAPSHOT.jar
else
	echo "failed to build - see build.log"
fi