= Report runner service
Steve Schafer;
:doctype: article
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

= Overview

Report runner service is a microservice for generating BIRT reports.

We attempt to adhere to REST standards although running a report is really an action and not a resource.  However we use POST for report run actions because it can be thought of as adding a new request, where a request is a resource.  We use GET for retrieving reports and report status.

When the payload is the generated report, it is returned with the appropriate MIME type and a response code of 200.  If there was an error generating the report, a response code of 500 (internal server error) is returned.  If the report design file was not found, 404 (not found) is returned.  If the output format is not recognized, 406 (not acceptable) is returned.

The server can be configured to use the open-source BIRT libraries or the OpenText commercial BIRT libraries.

= Requests

include::run-api.adoc[]

include::submit-api.adoc[]


TODO

= Configuring for OpenText libraries

If you have purchased the OpenText commercial iHub, iServer or Java Components products you can build 
this REST server
to use the commercial libraries.  There are two directories you will need to locate: lib and platform.  In the iServer installation they will be in iServer/Jar/BIRT.  In the case of OJC, they are in WEB-INF in the OJC webapp.  The jars in lib are used during the maven build and the jars in platform/plugins are used at runtime.

. Use the bash script mvn-install-birt-jars to install the commercial jars into your local maven repository.  For example, assuming a standard Actuate 11 iServer installation:
+
------
./mvn-install-birt-jars "/c/Program Files (x86)/Actuate11sp6/iServer/Jar/BIRT/lib"
------
+
This works from the git-bash shell on windows, available from https://git-scm.com/downloads.

. Rename pom.xml to pom-os.xml and pom-actuate.xml to pom.xml.  

. Build with
+
------
mvn package
------

. Make sure your runtime properties file is correctly set up for the commercial jars:
 .. set birt.runner.isActuate to true.
 .. set birt.runner.runtime to the platform directory.
For example:
+
------
birt.runner.isActuate=true
birt.runner.runtime=C:/Program Files (x86)/Actuate11sp6/iServer/Jar/BIRT/platform
------

======
Note that if you use backslashes in a java properties file they must be doubled, like this: 
C:\\Program Files (x86)\\Actuate11sp6\\iServer\\Jar\\BIRT\\platform.  
Single forward slashes can also be used.  On Windows they will be automatically converted to backslashes.
======

= Startup

To start change directory to the target folder under the root folder (the folder containing pom.xml) and type:

------
java -jar BIRT-Report-Runner-REST-Service-0.0.1-SNAPSHOT.jar
------
